function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = -1000000; // objWorld
	global.__objectDepths[1] = 0; // objCamera
	global.__objectDepths[2] = 0; // objPlayMusic
	global.__objectDepths[3] = 0; // objTitleMenu
	global.__objectDepths[4] = 0; // objDifficultyMenu
	global.__objectDepths[5] = 0; // objOptionsMenu
	global.__objectDepths[6] = 0; // objKeyboardControlsMenu
	global.__objectDepths[7] = 0; // objControllerMenu
	global.__objectDepths[8] = -10; // objPlayerStart
	global.__objectDepths[9] = -10; // objPlayer
	global.__objectDepths[10] = -11; // objBow
	global.__objectDepths[11] = -1; // objBullet
	global.__objectDepths[12] = 0; // objBloodEmitter
	global.__objectDepths[13] = -10; // objBlood
	global.__objectDepths[14] = -100; // objGameOver
	global.__objectDepths[15] = -10; // objPlayerHit
	global.__objectDepths[16] = -11; // objDeathExplosion
	global.__objectDepths[17] = -10; // objGodzillaGameOver
	global.__objectDepths[18] = -10; // objGodzillaDoll
	global.__objectDepths[19] = 100; // objBlock
	global.__objectDepths[20] = 0; // objBlockDynamic
	global.__objectDepths[21] = 100; // objMiniBlock
	global.__objectDepths[22] = 100; // objIceBlock
	global.__objectDepths[23] = 0; // objBlockInvis
	global.__objectDepths[24] = 0; // objBlockFake
	global.__objectDepths[25] = 100; // objConveyor
	global.__objectDepths[26] = 100; // objConveyorL
	global.__objectDepths[27] = 100; // objConveyorR
	global.__objectDepths[28] = 1; // objBossBlock
	global.__objectDepths[29] = 0; // objSaveBlocker
	global.__objectDepths[30] = 100; // objSlope
	global.__objectDepths[31] = 100; // objSlopeDownLeft
	global.__objectDepths[32] = 100; // objSlopeDownRight
	global.__objectDepths[33] = 100; // objSlopeUpLeft
	global.__objectDepths[34] = 100; // objSlopeUpRight
	global.__objectDepths[35] = 1; // objPlatform
	global.__objectDepths[36] = 1; // objPlatformInvisible
	global.__objectDepths[37] = 1; // objPlatformTouch
	global.__objectDepths[38] = 0; // objPlayerKiller
	global.__objectDepths[39] = 10; // objSpikeUp
	global.__objectDepths[40] = 10; // objSpikeRight
	global.__objectDepths[41] = 10; // objSpikeLeft
	global.__objectDepths[42] = 10; // objSpikeDown
	global.__objectDepths[43] = 10; // objMiniUp
	global.__objectDepths[44] = 10; // objMiniRight
	global.__objectDepths[45] = 10; // objMiniLeft
	global.__objectDepths[46] = 10; // objMiniDown
	global.__objectDepths[47] = 0; // objCherry
	global.__objectDepths[48] = 0; // objCherryBounce
	global.__objectDepths[49] = 0; // objCherryBounceRandom
	global.__objectDepths[50] = 0; // objCherryBounceLat
	global.__objectDepths[51] = 0; // objCherryBounceVert
	global.__objectDepths[52] = 0; // objKillerBlock
	global.__objectDepths[53] = 0; // objCherryEnemyTest
	global.__objectDepths[54] = 0; // objCherryBossTest
	global.__objectDepths[55] = 10; // objMiku
	global.__objectDepths[56] = 0; // objCherryRandomCol
	global.__objectDepths[57] = 0; // objCherryRandomColExplode
	global.__objectDepths[58] = 0; // objCherryRandomColBounce
	global.__objectDepths[59] = 0; // objTriggerManager
	global.__objectDepths[60] = 0; // objTrigger
	global.__objectDepths[61] = 15; // objTriggerButtonR
	global.__objectDepths[62] = 15; // objTriggerButtonL
	global.__objectDepths[63] = -50; // objWater
	global.__objectDepths[64] = -50; // objWater2
	global.__objectDepths[65] = -50; // objWater3
	global.__objectDepths[66] = 11; // objVineR
	global.__objectDepths[67] = 11; // objVineL
	global.__objectDepths[68] = 0; // objJumpRefresher
	global.__objectDepths[69] = -5; // objSign
	global.__objectDepths[70] = 0; // objGravityUp
	global.__objectDepths[71] = 0; // objGravityDown
	global.__objectDepths[72] = 1; // objSaveMedium
	global.__objectDepths[73] = 1; // objSave
	global.__objectDepths[74] = 1; // objSaveVHard
	global.__objectDepths[75] = 1; // objSaveMediumFlip
	global.__objectDepths[76] = 1; // objSaveFlip
	global.__objectDepths[77] = 1; // objSaveVHardFlip
	global.__objectDepths[78] = 0; // objWarpStart
	global.__objectDepths[79] = 10; // objRoomChanger
	global.__objectDepths[80] = 0; // objWarp
	global.__objectDepths[81] = 0; // objWarpNext
	global.__objectDepths[82] = 10; // objOutsideRoomChanger
	global.__objectDepths[83] = 0; // objSecretItem
	global.__objectDepths[84] = 0; // objSecretIndicator
	global.__objectDepths[85] = 0; // objBossItem
	global.__objectDepths[86] = 0; // objBossIndicator
	global.__objectDepths[87] = 0; // objGameClear
	global.__objectDepths[88] = 0; // objMainAvoidance
	global.__objectDepths[89] = 1; // objBullet01
	global.__objectDepths[90] = 1; // objBulletIntro
	global.__objectDepths[91] = 2; // objBulletTail
	global.__objectDepths[92] = 1; // objBulletBigFloat
	global.__objectDepths[93] = 1; // objBulletBigCircles
	global.__objectDepths[94] = 1; // objBulletBoing
	global.__objectDepths[95] = 1; // objBulletBigSlow
	global.__objectDepths[96] = 1; // objBulletFastSpin
	global.__objectDepths[97] = 1; // objBulletScreenFast
	global.__objectDepths[98] = 1; // objBulletBigSpam
	global.__objectDepths[99] = 0; // objBulletButterflySpam
	global.__objectDepths[100] = 1; // objBulletFakeRise
	global.__objectDepths[101] = 1000001; // objAreYouAlone
	global.__objectDepths[102] = 1; // objBulletView
	global.__objectDepths[103] = 1; // objBulletBigAni
	global.__objectDepths[104] = 1; // objBulletLunaCircle
	global.__objectDepths[105] = 0; // objBulletInvisSpin
	global.__objectDepths[106] = 1; // objBulletFalling
	global.__objectDepths[107] = 1; // objBulletBigBurst
	global.__objectDepths[108] = 1; // objBulletSlowFast
	global.__objectDepths[109] = 1; // objBulletFakeCenter
	global.__objectDepths[110] = 2; // objBulletBounceScreen
	global.__objectDepths[111] = 1; // objBulletStop
	global.__objectDepths[112] = 1; // objBulletSmall
	global.__objectDepths[113] = 0; // objBulletCurving
	global.__objectDepths[114] = 1; // objBulletPreparate
	global.__objectDepths[115] = 1; // objBulletFinalSpin
	global.__objectDepths[116] = 1; // objBulletOutsideView
	global.__objectDepths[117] = 1; // objBulletFinalSlow
	global.__objectDepths[118] = 1; // objBulletCircleFinal
	global.__objectDepths[119] = 1; // objBulletBigFinal
	global.__objectDepths[120] = 1; // objBulletFinalSpam
	global.__objectDepths[121] = 15; // objLittleReminder
	global.__objectDepths[122] = 0; // objResultScreen
	global.__objectDepths[123] = -1; // objPlatformGray
	global.__objectDepths[124] = 1; // objBulletSlowWall
	global.__objectDepths[125] = 1; // objBulletMiniBall
	global.__objectDepths[126] = 1; // objBulletKunaiTail
	global.__objectDepths[127] = -50; // objLightEffect
	global.__objectDepths[128] = -10; // objFakePlayer
	global.__objectDepths[129] = 1; // objBulletMiniBurst
	global.__objectDepths[130] = 1; // objBulletFakeAlp
	global.__objectDepths[131] = -15; // objInfoWaiting
	global.__objectDepths[132] = -10; // objSaveWaiting
	global.__objectDepths[133] = -50; // objHitCount
	global.__objectDepths[134] = 0; // objWarpPractice
	global.__objectDepths[135] = 10; // objProfileClear
	global.__objectDepths[136] = 5; // objTextClear
	global.__objectDepths[137] = 10; // objSuitmationTitle


	global.__objectNames[0] = "objWorld";
	global.__objectNames[1] = "objCamera";
	global.__objectNames[2] = "objPlayMusic";
	global.__objectNames[3] = "objTitleMenu";
	global.__objectNames[4] = "objDifficultyMenu";
	global.__objectNames[5] = "objOptionsMenu";
	global.__objectNames[6] = "objKeyboardControlsMenu";
	global.__objectNames[7] = "objControllerMenu";
	global.__objectNames[8] = "objPlayerStart";
	global.__objectNames[9] = "objPlayer";
	global.__objectNames[10] = "objBow";
	global.__objectNames[11] = "objBullet";
	global.__objectNames[12] = "objBloodEmitter";
	global.__objectNames[13] = "objBlood";
	global.__objectNames[14] = "objGameOver";
	global.__objectNames[15] = "objPlayerHit";
	global.__objectNames[16] = "objDeathExplosion";
	global.__objectNames[17] = "objGodzillaGameOver";
	global.__objectNames[18] = "objGodzillaDoll";
	global.__objectNames[19] = "objBlock";
	global.__objectNames[20] = "objBlockDynamic";
	global.__objectNames[21] = "objMiniBlock";
	global.__objectNames[22] = "objIceBlock";
	global.__objectNames[23] = "objBlockInvis";
	global.__objectNames[24] = "objBlockFake";
	global.__objectNames[25] = "objConveyor";
	global.__objectNames[26] = "objConveyorL";
	global.__objectNames[27] = "objConveyorR";
	global.__objectNames[28] = "objBossBlock";
	global.__objectNames[29] = "objSaveBlocker";
	global.__objectNames[30] = "objSlope";
	global.__objectNames[31] = "objSlopeDownLeft";
	global.__objectNames[32] = "objSlopeDownRight";
	global.__objectNames[33] = "objSlopeUpLeft";
	global.__objectNames[34] = "objSlopeUpRight";
	global.__objectNames[35] = "objPlatform";
	global.__objectNames[36] = "objPlatformInvisible";
	global.__objectNames[37] = "objPlatformTouch";
	global.__objectNames[38] = "objPlayerKiller";
	global.__objectNames[39] = "objSpikeUp";
	global.__objectNames[40] = "objSpikeRight";
	global.__objectNames[41] = "objSpikeLeft";
	global.__objectNames[42] = "objSpikeDown";
	global.__objectNames[43] = "objMiniUp";
	global.__objectNames[44] = "objMiniRight";
	global.__objectNames[45] = "objMiniLeft";
	global.__objectNames[46] = "objMiniDown";
	global.__objectNames[47] = "objCherry";
	global.__objectNames[48] = "objCherryBounce";
	global.__objectNames[49] = "objCherryBounceRandom";
	global.__objectNames[50] = "objCherryBounceLat";
	global.__objectNames[51] = "objCherryBounceVert";
	global.__objectNames[52] = "objKillerBlock";
	global.__objectNames[53] = "objCherryEnemyTest";
	global.__objectNames[54] = "objCherryBossTest";
	global.__objectNames[55] = "objMiku";
	global.__objectNames[56] = "objCherryRandomCol";
	global.__objectNames[57] = "objCherryRandomColExplode";
	global.__objectNames[58] = "objCherryRandomColBounce";
	global.__objectNames[59] = "objTriggerManager";
	global.__objectNames[60] = "objTrigger";
	global.__objectNames[61] = "objTriggerButtonR";
	global.__objectNames[62] = "objTriggerButtonL";
	global.__objectNames[63] = "objWater";
	global.__objectNames[64] = "objWater2";
	global.__objectNames[65] = "objWater3";
	global.__objectNames[66] = "objVineR";
	global.__objectNames[67] = "objVineL";
	global.__objectNames[68] = "objJumpRefresher";
	global.__objectNames[69] = "objSign";
	global.__objectNames[70] = "objGravityUp";
	global.__objectNames[71] = "objGravityDown";
	global.__objectNames[72] = "objSaveMedium";
	global.__objectNames[73] = "objSave";
	global.__objectNames[74] = "objSaveVHard";
	global.__objectNames[75] = "objSaveMediumFlip";
	global.__objectNames[76] = "objSaveFlip";
	global.__objectNames[77] = "objSaveVHardFlip";
	global.__objectNames[78] = "objWarpStart";
	global.__objectNames[79] = "objRoomChanger";
	global.__objectNames[80] = "objWarp";
	global.__objectNames[81] = "objWarpNext";
	global.__objectNames[82] = "objOutsideRoomChanger";
	global.__objectNames[83] = "objSecretItem";
	global.__objectNames[84] = "objSecretIndicator";
	global.__objectNames[85] = "objBossItem";
	global.__objectNames[86] = "objBossIndicator";
	global.__objectNames[87] = "objGameClear";
	global.__objectNames[88] = "objMainAvoidance";
	global.__objectNames[89] = "objBullet01";
	global.__objectNames[90] = "objBulletIntro";
	global.__objectNames[91] = "objBulletTail";
	global.__objectNames[92] = "objBulletBigFloat";
	global.__objectNames[93] = "objBulletBigCircles";
	global.__objectNames[94] = "objBulletBoing";
	global.__objectNames[95] = "objBulletBigSlow";
	global.__objectNames[96] = "objBulletFastSpin";
	global.__objectNames[97] = "objBulletScreenFast";
	global.__objectNames[98] = "objBulletBigSpam";
	global.__objectNames[99] = "objBulletButterflySpam";
	global.__objectNames[100] = "objBulletFakeRise";
	global.__objectNames[101] = "objAreYouAlone";
	global.__objectNames[102] = "objBulletView";
	global.__objectNames[103] = "objBulletBigAni";
	global.__objectNames[104] = "objBulletLunaCircle";
	global.__objectNames[105] = "objBulletInvisSpin";
	global.__objectNames[106] = "objBulletFalling";
	global.__objectNames[107] = "objBulletBigBurst";
	global.__objectNames[108] = "objBulletSlowFast";
	global.__objectNames[109] = "objBulletFakeCenter";
	global.__objectNames[110] = "objBulletBounceScreen";
	global.__objectNames[111] = "objBulletStop";
	global.__objectNames[112] = "objBulletSmall";
	global.__objectNames[113] = "objBulletCurving";
	global.__objectNames[114] = "objBulletPreparate";
	global.__objectNames[115] = "objBulletFinalSpin";
	global.__objectNames[116] = "objBulletOutsideView";
	global.__objectNames[117] = "objBulletFinalSlow";
	global.__objectNames[118] = "objBulletCircleFinal";
	global.__objectNames[119] = "objBulletBigFinal";
	global.__objectNames[120] = "objBulletFinalSpam";
	global.__objectNames[121] = "objLittleReminder";
	global.__objectNames[122] = "objResultScreen";
	global.__objectNames[123] = "objPlatformGray";
	global.__objectNames[124] = "objBulletSlowWall";
	global.__objectNames[125] = "objBulletMiniBall";
	global.__objectNames[126] = "objBulletKunaiTail";
	global.__objectNames[127] = "objLightEffect";
	global.__objectNames[128] = "objFakePlayer";
	global.__objectNames[129] = "objBulletMiniBurst";
	global.__objectNames[130] = "objBulletFakeAlp";
	global.__objectNames[131] = "objInfoWaiting";
	global.__objectNames[132] = "objSaveWaiting";
	global.__objectNames[133] = "objHitCount";
	global.__objectNames[134] = "objWarpPractice";
	global.__objectNames[135] = "objProfileClear";
	global.__objectNames[136] = "objTextClear";
	global.__objectNames[137] = "objSuitmationTitle";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
